AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Processes emarsys-recommendation-updates from 'emarsys-recommendation-updates' SQS and updates 'EmarsysRecommendaions' DynamoDB Table

Resources:
  EmarsysRecommendationUpdates:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: emarsys-recommendation-updates
      MessageRetentionPeriod: 86400 # 24 hours
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt EmarsysRecommendationUpdatesFailed.Arn
        maxReceiveCount: 5

  EmarsysRecommendationUpdatesFailed:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: emarsys-recommendation-updates-failed
      MessageRetentionPeriod: 604800 # 7 days in seconds

  EmarsysRecommendations:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: EmarsysRecommendations
      AttributeDefinitions:
        - AttributeName: email_hash
          AttributeType: 'S'
        - AttributeName: user_id
          AttributeType: 'N'
        - AttributeName: predictUserID
          AttributeType: 'S'
        - AttributeName: predictSecret
          AttributeType: 'S'
      KeySchema:
        - AttributeName: email_hash
          KeyType: HASH
        - AttributeName: user_id
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10

  EmarsysRecommendationsWriteCapacityScalableTarget: 
    Type: "AWS::ApplicationAutoScaling::ScalableTarget"
    Properties: 
      MaxCapacity: 1000
      MinCapacity: 5
      ResourceId: !Sub table/${EmarsysRecommendations}
      RoleARN: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable
      ScalableDimension: "dynamodb:table:WriteCapacityUnits"
      ServiceNamespace: dynamodb

  EmarsysRecommendationsWriteScalingPolicy: 
    Type: "AWS::ApplicationAutoScaling::ScalingPolicy"
    Properties: 
      PolicyName: EmarsysRecommendationsWriteAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref EmarsysRecommendationsWriteCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration: 
        TargetValue: 70
        ScaleInCooldown: 0
        ScaleOutCooldown: 0
        PredefinedMetricSpecification: 
          PredefinedMetricType: DynamoDBWriteCapacityUtilization


  EmarsysRecommendationsReadCapacityScalableTarget: 
    Type: "AWS::ApplicationAutoScaling::ScalableTarget"
    Properties: 
      MaxCapacity: 20
      MinCapacity: 5
      ResourceId: !Sub table/${EmarsysRecommendations}
      RoleARN: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable
      ScalableDimension: "dynamodb:table:ReadCapacityUnits"
      ServiceNamespace: dynamodb

  UserTableReadScalingPolicy: 
    Type: "AWS::ApplicationAutoScaling::ScalingPolicy"
    Properties: 
      PolicyName: EmarsysRecommendationsReadAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref EmarsysRecommendationsReadCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration: 
        TargetValue: 70
        ScaleInCooldown: 0
        ScaleOutCooldown: 0
        PredefinedMetricSpecification: 
          PredefinedMetricType: DynamoDBReadCapacityUtilization

  
  EmarsysRecommendationUpdatesProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: opt-in-subscriber-updates-processor
      Description: Processes opt-in messages subscriber updates from 'opt-in-subscriber-updates' SQS and updates 'EmarsysRecommendaions' DynamoDB Table
      Runtime: nodejs12.x
      Handler: src/opt-in-subscriber-updates-processor.handler
      Environment:
        Variables:
          DYANMO_DB_TABLE_NAME: !Ref EmarsysRecommendaions
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt EmarsysRecommendationUpdates.Arn
            BatchSize: 10
            Enabled: true
      MemorySize: 128
      Timeout: 25
      ReservedConcurrentExecutions: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBWritePolicy:
            TableName: !Ref EmarsysRecommendaions
