AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Processes opt-in messages subscriber updates from 'opt-in-subscriber-updates' SQS and updates 'OptInSubscribers' DynamoDB Table

Resources:
  OptInSubscriberUpdates:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: opt-in-subscriber-updates
      MessageRetentionPeriod: 86400 # 24 hours
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt OptInSubscriberUpdatesFailed.Arn
        maxReceiveCount: 5

  OptInSubscriberUpdatesFailed:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: opt-in-subscriber-updates-failed
      MessageRetentionPeriod: 604800 # 7 days in seconds

  OptInSubscribers:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: OptInSubscribers
      AttributeDefinitions:
        - AttributeName: email_hash
          AttributeType: 'S'
        - AttributeName: user_id
          AttributeType: 'N'
      KeySchema:
        - AttributeName: email_hash
          KeyType: HASH
        - AttributeName: user_id
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10

  OptInSubscribersWriteCapacityScalableTarget: 
    Type: "AWS::ApplicationAutoScaling::ScalableTarget"
    Properties: 
      MaxCapacity: 1000
      MinCapacity: 5
      ResourceId: !Sub table/${OptInSubscribers}
      RoleARN: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable
      ScalableDimension: "dynamodb:table:WriteCapacityUnits"
      ServiceNamespace: dynamodb

  OptInSubscribersWriteScalingPolicy: 
    Type: "AWS::ApplicationAutoScaling::ScalingPolicy"
    Properties: 
      PolicyName: OptInSubscribersWriteAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref OptInSubscribersWriteCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration: 
        TargetValue: 70
        ScaleInCooldown: 0
        ScaleOutCooldown: 0
        PredefinedMetricSpecification: 
          PredefinedMetricType: DynamoDBWriteCapacityUtilization


  OptInSubscribersReadCapacityScalableTarget: 
    Type: "AWS::ApplicationAutoScaling::ScalableTarget"
    Properties: 
      MaxCapacity: 20
      MinCapacity: 5
      ResourceId: !Sub table/${OptInSubscribers}
      RoleARN: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable
      ScalableDimension: "dynamodb:table:ReadCapacityUnits"
      ServiceNamespace: dynamodb

  UserTableReadScalingPolicy: 
    Type: "AWS::ApplicationAutoScaling::ScalingPolicy"
    Properties: 
      PolicyName: OptInSubscribersReadAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref OptInSubscribersReadCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration: 
        TargetValue: 70
        ScaleInCooldown: 0
        ScaleOutCooldown: 0
        PredefinedMetricSpecification: 
          PredefinedMetricType: DynamoDBReadCapacityUtilization

  
  OptInSubscriberUpdatesProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: opt-in-subscriber-updates-processor
      Description: Processes opt-in messages subscriber updates from 'opt-in-subscriber-updates' SQS and updates 'OptInSubscribers' DynamoDB Table
      Runtime: nodejs12.x
      Handler: src/opt-in-subscriber-updates-processor.handler
      Environment:
        Variables:
          DYANMO_DB_TABLE_NAME: !Ref OptInSubscribers
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt OptInSubscriberUpdates.Arn
            BatchSize: 10
            Enabled: true
      MemorySize: 128
      Timeout: 25
      ReservedConcurrentExecutions: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBWritePolicy:
            TableName: !Ref OptInSubscribers
